from enum import Enum


class TaskHistoryEventType(Enum):
    CREATED = "CREATED"
    TITLE_CHANGED = "TITLE_CHANGED"
    STATUS_CHANGED = "STATUS_CHANGED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    DATES_CHANGED = "DATES_CHANGED"
    ASSIGNEE_CHANGED = "ASSIGNEE_CHANGED"
    DESCRIPTION_UPDATED = "DESCRIPTION_UPDATED"
    MOVED = "MOVED"
    TYPE_CHANGED = "TYPE_CHANGED"
